/* XPDefinitions.h
 * Define all stuff from "Data Input & Output" in X-Plane
 *
 * X-Plane Version: 9.61RC2
 *
 */

#define XP_DEFINITIONS_VERS	"9.61RC2"

#define XP_FRAMERATE			0
#define XP_TIMES			1
#define XP_SIM_STATS			2

#define XP_SPEED_VERTICAL_SPEED		3
#define XP_MACH_GLOAD			4

#define XP_ATMOSPHERE_WEATHER		5
#define XP_ATMOSPHERE_AIRCRAFT		6
#define XP_SYSTEM_PRESSURES		7

#define XP_JOYSTICK_1_AIL_ELV_RUD	8
#define XP_OTHER_FLIGHT_CONTROLS	9
#define XP_ARTSTAB_AIL_ELV_RUD		10
#define XP_FLIGHTCON_AIL_ELV_RUD	11

#define XP_WINGSWEEP_THRUST_VECT	12
#define XP_TRIM_FLAP_SLAT_SBRAKES	13
#define XP_GEAR_BRAKES			14

#define XP_ANGULAR_MOMENTS		15
#define XP_ANGULAR_ACCELERATIONS	16
#define XP_ANGULAR_VELOCITIES		17
#define XP_PITCH_ROLL_HEADINGS		18
#define XP_AOA_SIDESLIP_PATHS		19

#define XP_LAT_LON_ALTITUDE		20
#define XP_LOC_VEL_DIST_TRAVELLED	21

#define XP_ALL_PLANES_LAT		22
#define XP_ALL_PLANES_LON		23
#define XP_ALL_PLANES_ALT		24

#define XP_THROTTLE_COMMAND		25
#define XP_THROTTLE_ACTUAL		26
#define XP_FEATHER_NORM_BETA_REVERS	27
#define XP_PROP_SETTING			28
#define XP_MIXTURE_SETTING		29
#define XP_CARB_HEAT_SETTING		30
#define XP_COWL_FLAP_SETTING		31
#define XP_IGNITION_SETTING		32

#define XP_STARTER_TIMEOUT		33
#define XP_ENGINE_POWER			34
#define XP_ENGINE_THRUST		35
#define XP_ENGINE_TORQUE		36
#define XP_ENGINE_RPM			37
#define XP_PROP_RPM			38
#define XP_PROP_PITCH			39
#define XP_PROPWASH_JETWASH		40
#define XP_N1				41
#define XP_N2				42
#define XP_MP				43
#define XP_EPR				44
#define XP_FF				45
#define XP_ITT				46
#define XP_EGT				47
#define XP_CHT				48
#define XP_OIL_PRESSURE			49
#define XP_OIL_TEMP			50
#define XP_FUEL_PRESSURE		51
#define XP_GENERATOR_AMPERAGE		52
#define XP_BATTERY_AMPERAGE		53
#define XP_BATTERY_VOLTAGE		54

#define XP_FUEL_PUMP			55
#define XP_IDLE_SPEED			56
#define XP_BATTERY			57
#define XP_GENERATOR			58
#define XP_INVERTER			59
#define XP_FADEC			60
#define XP_IGNITER			61
                                        
#define XP_FUEL_WEIGHTS			62
#define XP_PAYLOAD_AND_CG		63
                                        
#define XP_AERO_FORCES			64
#define XP_ENGINE_FORCES		65
#define XP_LANDING_GEAR_VERT_FORCE	66
#define XP_LANDING_GEAR_DEPLOYMENT	67

#define XP_AERO_FORCES			68
#define XP_PROP_EFFICIENCY		69

#define XP_DEFS_AILERONS_1		70
#define XP_DEFS_AILERONS_2		71
#define XP_DEFS_ROLL_SPOILERS_1		72
#define XP_DEFS_ROLL_SPOILERS_2		73
#define XP_DEFS_ELEVATORS		74
#define XP_DEFS_RUDDERS			75
#define XP_DEFS_YAW_BRAKES		76
#define XP_CONTROL_FORCES		77

#define XP_TOTAL_VERT_THRUST_VECTS	78
#define XP_TOTAL_LAT_THRUST_VECTS	79
#define XP_PITCH_CYCLIC_DISC_TILTS	80
#define XP_ROLL_CYCLIC_DISC_TITLS	81
#define XP_PITCH_CYCLIC_FLAPPING	82
#define XP_ROLL_CYCLIC_FLAPPING		83

#define XP_GRND_EFFECT_LIFT_WINGS	84
#define XP_GRND_EFFECT_DRAG_WINGS	85
#define XP_GRND_EFFECT_WASH_WINGS	86
#define XP_GRND_EFFECT_LIFT_STABS	87
#define XP_GRND_EFFECT_DRAG_STABS	88
#define XP_GRND_EFFECT_WASH_STABS	89
#define XP_GRND_EFFECT_LIFT_PROPS	90
#define XP_GRND_EFFECT_DRAG_PROPS	91

#define XP_WING_LIFT			92
#define XP_WING_DRAG			93
#define XP_STAB_LIFT			94
#define XP_STAB_DRAG			95
                                        
#define XP_COMM_1_2_FREQ		96
#define XP_NAV_1_2_FREQ			97
#define XP_NAV_1_2_OBS			98
#define XP_NAV_1_DEFLECTIONS		99
#define XP_NAV_2_DEFLECTIONS		100
#define XP_ADF_1_2_STATUS		101
#define XP_DME_STATUS			102
#define XP_GPS_STATUS			103
#define XP_XPNDR_STATUS			104
#define XP_MARKER_STATUS		105
                                        
#define XP_SWITCHES_1_ELECTRICAL	106
#define XP_SWITCHES_2_EFIS		107
#define XP_SWITCHES_3_AP_FDIR_HUD	108
#define XP_SWITCHES_4_ANTI_ICE		109
#define XP_SWITCHES_5_ANTI_ICE_FUEL	110
#define XP_SWITCHES_6_CLUTCH_ASTAB	110
#define XP_SWITCHES_7_MISC		112

#define XP_ANNUNCIATORS_GENERAL		113
#define XP_ANNUNCIATORS_GENERAL_2	114
#define XP_ANNUNCIATORS_ENGINE		115

#define XP_AUTOPILOT_ARMS		116
#define XP_AUTOPILOT_MODES		117
#define XP_AUTOPILOT_VALUES		118

#define XP_WEAPON_STATUS		119
#define XP_PRESSURIZATION_STATUS	120
#define XP_APU_GPU_STATUS		121
#define XP_RADAR_STATUS			122
#define XP_HYDRAULIC_STATUS		123
#define XP_ELECTRIC_SOLAR_STATUS	124
#define XP_ICING_STATUS_1		125
#define XP_ICING_STATUS_2		126
#define XP_WARNING_STATUS		127
#define XP_FLITE_PLAN_LEGS		128

#define XP_HARDWARE_OPTIONS		129
#define XP_CAMERA_LOCATION		130
#define XP_GROUND_LOCATION		131

/* ???
#define XP_FAILURE_STATE_1_3_1		128
#define XP_FAILURE_STATE_1_3_2		129
#define XP_FAILURE_STATE_1_3_3		130
*/